services:
  - type: web
    name: quami
    env: node
    region: oregon
    plan: free
    buildCommand: rm -rf node_modules && npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.15.1
