import type { App } from 'vue';
import SolanaWallets from 'solana-wallets-vue';
import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
import {
  AlphaWalletAdapter,
  AvanaWalletAdapter,
  BitKeepWalletAdapter,
  BitpieWalletAdapter,
  CloverWalletAdapter,
  Coin98WalletAdapter,
  CoinbaseWalletAdapter,
  CoinhubWalletAdapter,
  FractalWalletAdapter,
  HuobiWalletAdapter,
  HyperpayWalletAdapter,
  KeystoneWalletAdapter,
  KrystalWalletAdapter,
  LedgerWalletAdapter,
  MathWalletAdapter,
  NekoWalletAdapter,
  NightlyWalletAdapter,
  NufiWalletAdapter,
  OntoWalletAdapter,
  ParticleWalletAdapter,
  PhantomWalletAdapter,
  SafePalWalletAdapter,
  SaifuWalletAdapter,
  SalmonWalletAdapter,
  SkyWalletAdapter,
  SolflareWalletAdapter,
  SolongWalletAdapter,
  SpotWalletAdapter,
  TokenaryWalletAdapter,
  TokenPocketWalletAdapter,
  TorusWalletAdapter,
  TrezorWalletAdapter,
  TrustWalletAdapter,
  UnsafeBurnerWalletAdapter,
  XDEFIWalletAdapter,
} from '@solana/wallet-adapter-wallets';

export default {
  install(app: App) {
    const network = (import.meta.env.VITE_SOLANA_NETWORK || 'devnet') as WalletAdapterNetwork;

    const walletOptions = {
      // Phantom first so it is treated as the primary / recommended wallet
      wallets: [
        new PhantomWalletAdapter(),
        new SolflareWalletAdapter({ network }),
        new CoinbaseWalletAdapter(),
        new LedgerWalletAdapter(),
        new TrustWalletAdapter(),
        new Coin98WalletAdapter(),
        new SafePalWalletAdapter(),
        new TokenPocketWalletAdapter(),
        new NightlyWalletAdapter(),
        new AlphaWalletAdapter(),
        new AvanaWalletAdapter(),
        new BitKeepWalletAdapter(),
        new BitpieWalletAdapter(),
        new CloverWalletAdapter(),
        new CoinhubWalletAdapter(),
        new FractalWalletAdapter(),
        new HuobiWalletAdapter(),
        new HyperpayWalletAdapter(),
        new KeystoneWalletAdapter(),
        new KrystalWalletAdapter(),
        new MathWalletAdapter(),
        new NekoWalletAdapter(),
        new NufiWalletAdapter(),
        new OntoWalletAdapter(),
        new ParticleWalletAdapter(),
        new SaifuWalletAdapter(),
        new SalmonWalletAdapter(),
        new SkyWalletAdapter(),
        new SolongWalletAdapter(),
        new SpotWalletAdapter(),
        new TokenaryWalletAdapter(),
        new TorusWalletAdapter(),
        new TrezorWalletAdapter(),
        new UnsafeBurnerWalletAdapter(),
        new XDEFIWalletAdapter(),
      ],
      autoConnect: true,
    };

    app.use(SolanaWallets, walletOptions);
  },
};
