import { getRandomHexColor, getRandomBoolean } from '../../../utils/randoms.js'
import type { BlobXyzOptionsConfig } from './types.js'

/**
 * Default configuration for blob behavior and appearance
 */
export const defaultBlobXyzConfig: BlobXyzOptionsConfig = {
  spikes: {
    min: 0,
    max: 20,
    step: 0.1,
    digits: 2,
    rMin: 0.15,
    rMax: 4.0,
    default: 0.2,
  },
  speed: {
    min: 20,
    max: 50,
    default: 20,
  },
  processing: {
    min: 0.4,
    max: 1,
    default: 0.5,
  },
  resolution: {
    min: 120,
    max: 220,
    default: 180,
    step: 1,
  },
  skins: {
    presets: {
      radial: {
        wireframe: getRandomBoolean(0.1),
        lightPosition: { x: 1000, y: 2500, z: 200 },
        shininess: 50,
        color1: getRandomHexColor(),
        color2: getRandomHexColor(),
        color3: getRandomHexColor(),
        opacity: 1,
      },
      banded: {
        wireframe: getRandomBoolean(0.1),
        lightPosition: { x: 800, y: 2200, z: 300 },
        shininess: 45,
        color1: getRandomHexColor(),
        color2: getRandomHexColor(),
        color3: getRandomHexColor(),
        opacity: 1,
      },
      striped: {
        wireframe: false,
        lightPosition: { x: 0, y: 500, z: 200 },
        shininess: 50,
        opacity: 1,
        color1: '#ff0066',
        color2: '#00ff66',
        color3: '#6600ff',
      },
      marble: {
        wireframe: false,
        lightPosition: { x: 600, y: 2000, z: 400 },
        shininess: 65,
        color1: getRandomHexColor(),
        color2: getRandomHexColor(),
        color3: getRandomHexColor(),
        opacity: 1,
      },
      fresnel: {
        wireframe: false,
        lightPosition: { x: 500, y: 1800, z: 500 },
        shininess: 120,
        color1: getRandomHexColor(),
        color2: getRandomHexColor(),
        color3: getRandomHexColor(),
        opacity: 0.9,
      },
      iridescent: {
        wireframe: false,
        lightPosition: { x: 800, y: 2200, z: 300 },
        shininess: 90,
        color1: getRandomHexColor(),
        color2: getRandomHexColor(),
        color3: getRandomHexColor(),
        opacity: 1,
      },
      spiral: {
        wireframe: false,
        lightPosition: { x: 900, y: 2400, z: 250 },
        shininess: 55,
        color1: getRandomHexColor(),
        color2: getRandomHexColor(),
        color3: getRandomHexColor(),
        opacity: 1,
      },
      plasma: {
        wireframe: false,
        lightPosition: { x: 700, y: 2000, z: 350 },
        shininess: 40,
        color1: getRandomHexColor(),
        color2: getRandomHexColor(),
        color3: getRandomHexColor(),
        opacity: 1,
      },
      gradient: {
        wireframe: false,
        lightPosition: { x: 500, y: 2500, z: 200 },
        shininess: 70,
        color1: getRandomHexColor(),
        color2: getRandomHexColor(),
        color3: getRandomHexColor(),
        opacity: 1,
      },
      matte: {
        wireframe: false,
        lightPosition: { x: 800, y: 2000, z: 400 },
        shininess: 10,
        color1: '#7c8fa6',
        color2: '#7c8fa6',
        color3: '#7c8fa6',
        opacity: 1,
      },
      glossy: {
        wireframe: false,
        lightPosition: { x: 1000, y: 2500, z: 300 },
        shininess: 150,
        color1: '#e84393',
        color2: '#e84393',
        color3: '#e84393',
        opacity: 1,
      },
      metallic: {
        wireframe: false,
        lightPosition: { x: 900, y: 2200, z: 350 },
        shininess: 120,
        color1: '#c0a060',
        color2: '#c0a060',
        color3: '#c0a060',
        opacity: 1,
      },
      subsurface: {
        wireframe: false,
        lightPosition: { x: 600, y: 1800, z: 500 },
        shininess: 30,
        color1: '#ff7675',
        color2: '#ff7675',
        color3: '#ff7675',
        opacity: 0.92,
      },
      chrome: {
        wireframe: false,
        lightPosition: { x: 1000, y: 2500, z: 200 },
        shininess: 180,
        color1: '#c0c0c0',
        color2: '#c0c0c0',
        color3: '#c0c0c0',
        opacity: 1,
      },
      clay: {
        wireframe: false,
        lightPosition: { x: 700, y: 2000, z: 400 },
        shininess: 25,
        color1: '#d4a574',
        color2: '#d4a574',
        color3: '#d4a574',
        opacity: 1,
      },
      jade: {
        wireframe: false,
        lightPosition: { x: 800, y: 2200, z: 350 },
        shininess: 80,
        color1: '#2ecc71',
        color2: '#2ecc71',
        color3: '#2ecc71',
        opacity: 1,
      },
      'toon-matcap': {
        wireframe: false,
        lightPosition: { x: 900, y: 2400, z: 250 },
        shininess: 40,
        color1: '#6c5ce7',
        color2: '#6c5ce7',
        color3: '#6c5ce7',
        opacity: 1,
      },
      hologram: {
        wireframe: false,
        lightPosition: { x: 600, y: 1800, z: 500 },
        shininess: 100,
        color1: '#00cec9',
        color2: '#00cec9',
        color3: '#00cec9',
        opacity: 0.85,
      },
      flat: {
        wireframe: false,
        lightPosition: { x: 800, y: 2500, z: 200 },
        shininess: 20,
        color1: '#fd79a8',
        color2: '#fd79a8',
        color3: '#fd79a8',
        opacity: 1,
      },
      stepped: {
        wireframe: false,
        lightPosition: { x: 800, y: 2200, z: 300 },
        shininess: 30,
        color1: '#0984e3',
        color2: '#74b9ff',
        color3: '#0984e3',
        opacity: 1,
      },
      halftone: {
        wireframe: false,
        lightPosition: { x: 900, y: 2400, z: 250 },
        shininess: 20,
        color1: '#2d3436',
        color2: '#dfe6e9',
        color3: '#2d3436',
        opacity: 1,
      },
      outlined: {
        wireframe: false,
        lightPosition: { x: 700, y: 2000, z: 350 },
        shininess: 40,
        color1: '#00b894',
        color2: '#00b894',
        color3: '#00b894',
        opacity: 1,
      },
    },
  },
}
